### ISSUE TITLE
Do we really need this?

### ISSUE THREAD

**Issue by miegl** [libretime/organization#1]
Hello,
it caught my eye that libretime has a code of conduct. And ever more so that it is based on contributor covenant. Do we really need this sjw crap?
Seriously, what has gender identity, race, religion, sexual identity and orientation to do with development and free software?
Please rethink this decision.
Thank you.

**Comment by Robbt** [comment]
There are a lot of reasons we have a code of conduct, discouraging "trollish" behaviour such as opening up an issue questioning the decision making and using disparaging terms such as sjw crap could be considered a violation of the code-of-conduct.

But seriously, even if for someone reason you think that being shitty to someone based upon their identity, race, religion or sexual identity is ok based upon some twisted logic there are plenty of other things covered in the "code of conduct" such as

    Using welcoming and inclusive language
    Being respectful of differing viewpoints and experiences
    Gracefully accepting constructive criticism
    Focusing on what is best for the community
    Showing empathy towards other community members

So yeah I'm going to close this issue now.

**Comment by hairmare** [comment]
I'm with @Robbt on this one.

> Do we really need this sjw crap?

Yes, you calling it "sjw crap" seems like a good enough reason.

Not discriminating folks based on their age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation has everything to do with being an inclusive community.

Given that we have the year 2018 and still only 20% of tech-jobs are held by women I think it's rather important to document and enforce a baseline standard regarding this. If you look for them you'll find that nowadays not only FOSS communities but also most private enterprises have and enforce rules to ensure that minorities aren't thrown under the bus.

**Comment by miegl** [comment]
> discouraging "trollish" behaviour such as opening up an issue questioning the decision making and using disparaging terms such as sjw crap

This question wasn't meant to troll anyone but rather to see the reason behind including this CoC.

> But seriously, even if for someone reason you think that being shitty to someone based upon their identity, race, religion or sexual identity is ok based upon some twisted logic

I didn't say it's ok. I just said that it has nothing to do with development and free software.

> Not discriminating folks based on their age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation has everything to do with being an inclusive community.

Seriously, ask yourself, what has this to do with software development?

> Given that we have the year 2018 and still only 20% of tech-jobs are held by women

Jeez! There's a reason why men are more likely to work in tech industry. Women are just biologically different than men. They excel in other fields. What's so hard to understand about this?

**Comment by Robbt** [comment]
Well you saw the reason. And honestly I am curious what specifically led you to feel like it was a good idea to open up a issue questioning a policy of a software project you have never contributed too. 

I feel like the intent here is something akin to the controversy and attention seeking variety. We as a project seek to create a positive environment where all are welcome to contribute code. So while you may disagree with this I see your post merely as a provocation seeking attention to your ideology and biases against people who seek inclusive projects. Since you evidently have nothing to share other than your opinion and political views (which have nothing to do with development and free software). You are welcome to leave so that I can focus on writing code rather than responding to your attempt at provoking a debate.

**Comment by miegl** [comment]
What led to my decision? Well the fact that you guys are embracing a coc that is destroying open source. Sure, I never contributed to this piece of software but that doesn't mean I never will. I'm interested in LibreTime since the day it has been created.

I appreciate your intent to create a positive environment, but this is just not the way to do it.
If you see my question as a provocation, there's probably something wrong. All I did was ask a question.

> You are welcome to leave

Wait, does that mean you are excluding me from this inclusive community?

Personally, I don't see why it's so important to have a code of conduct. I thought open source was about code, not about diversity. If you really think embracing this CoC is a good idea, you need to open your eyes quick before too late.

**Comment by Robbt** [comment]
Well I and others who are around disagree with you. I'm not excluding you because that just confirm your fears that there is some kind of conspiracy going on to destroy open source. The "code of conduct" isn't being used to destroy anything in here, the only time it has been addressed is when people are in general antagonistic. 

The "code of conduct" is a human tool for negotiation of problematic and disruptive behavior that can happen when people are jerks to each other. It is not the same as a "legal" tool such as a license where it is potentially negotiated by courts and other legal precedent. People can only use it to control others if they can convince other people to agree with them.

I disagree that it is problematic and/or destroying open source. My suggestion that you leave is basically me wanting to spend my energy solving software problems (which this project has many) vs. arguing with someone who is evidently convinced that there is a secret cabal plotting to destroy open source by creating rules that people should try to treat each other with respect and not be jerks based upon the various differences we have aside from coding style. Honestly an important part of the "code of conduct" is that people try to not be jerks towards each other when they disagree with each others opinions regarding code.

**Comment by miegl** [comment]
No, I don't think that there is some kind of conspiracy going on to destroy open source. I just think social justice is hurting open source as we know it.
I understand your intentions. But what I don't understand is why you would choose to embrace this extreme sjw kind of CoC instead of anything other.
I also don't understand what's so wrong about the fact that only about 20% tech jobs are held by women. Do you really think diversity is more important than the quality of code and talent?
With that I would like to thank you for your time that went into this debate. Have a nice day.

**Comment by hairmare** [comment]
Thanks for keeping the discussion civil. We do seem to disagree on this point. For me, software doesn't exist in a vacuum, it needs a community to nurture and sustain it. I consider healthy communities to be both inclusive and diverse. A healthy community also attracts talent. Code quality comes first as long as no one's an asshat anyway.

While I can try to see your point, I can't really find anything objectionable in our code of conduct. I support that we as a global community need to find space for this discussion but I also think that there isn't much merit to discuss the broader scoped (code of conduct/calling us sjws due to the code of conduct) issues here.

Please don't take this as us telling you to leave and go away. If you feel that the code of conduct somehow excludes you, we're glad to discuss this. If you would like to do so in a private forum you can get in touch with one of us on the LibreTime Slack or via a private message on the LibreTime Discourse.

We'd be happy to welcome you to our community. If you wish to invest your time in improving LibreTime, there is lots to be done like supporting the community, debugging and fixing bugs, refactoring legacy code and, implementing features.

I'm going to lock this thread now since I want it to finish on a positive note.

Thanks for reaching out to us. I really hope you understand the reasoning why we don't see a need to remove our code of conduct right now.
